language: go

go:
  - "1.10"

before_script:
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - go test -v -cover -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci